# Generated by Django 4.0 on 2022-06-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='DirectorName',
        ),
    ]
